spring:
  datasource:
    url: jdbc:postgresql://ep-super-wildflower-a131rdol-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_8VQS3gTYendA
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # mail:
  #   host: ${SPRING_MAIL_HOST}
  #   port: ${SPRING_MAIL_PORT}
  #   username: ${SPRING_MAIL_USERNAME}
  #   password: ${SPRING_MAIL_PASSWORD}
  #   properties:
  #     mail.smtp.auth: ${SPRING_MAIL_SMTP_AUTH:true}
  #     mail.smtp.starttls.enable: ${SPRING_MAIL_SMTP_STARTTLS:true}

server:
  port: ${PORT:8080}

