spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing_system
    username: postgres
    password: Kamal@1313#125
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: satwanikamal2003@gmail.com
    password: lwrf imuo akak cjbw
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 9090

